# Generated by Django 3.2.3 on 2021-05-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Fore'), (5, 'Five')], default=0, verbose_name='Рэйтинг')),
                ('status', models.CharField(choices=[('новая', 'новая'), ('модерированная', 'модерированная')], default='новая', max_length=50, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
    ]
