# Generated by Django 3.2.3 on 2021-05-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Fore'), (5, 'Five')], default=0, verbose_name='Рэйтинг'),
        ),
    ]
